<?php

namespace Technodrive\Mvc;

class LayoutModel extends ViewModel
{
    /**
     * View variables
     * @var array
     */
    protected array $variables;

    protected string $template = '';

    public function setTemplate(string $templateName): void
    {
        parent::setTemplate($templateName); // TODO: Change the autogenerated stub
    }

    public function setContent(string $content)
    {
        $this->variables['content'] = $content;
    }


}